### ISSUE TITLE
Properly handle sequence and read group metadata from BWA

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/cannoli#10]
We write out empty dictionaries:

```
scala> println(sc.loadAlignments("LP6005441-DNA_A01.bwa.adam").recordGroups)
RecordGroupDictionary()

scala> println(sc.loadAlignments("LP6005441-DNA_A01.bwa.adam").sequences)
SequenceDictionary{}
```

**Comment by heuermh** [comment]
I see what #11 is doing but I don't fully understand the issue. Shouldn't `LP6005441-DNA_A01.bwa.adam` contain a sequence dictionary on disk within the Parquet folder?

**Comment by fnothaft** [comment]
We copy the sequence dictionary from the unaligned reads, hence, the output sequence dictionary is empty.

**Comment by heuermh** [comment]
Ah right, we're starting from FASTQ.  The user would have to build the .dict from the bwa indices or from the FASTA reference first, I suppose.
