### ISSUE TITLE
RNA alignment

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/cannoli#105]
We should add some algorithm for RNA alignment

**Comment by heuermh** [comment]
What were you thinking?  Any external tool(s) will need to be smart about handling stdin and stdout.

**Comment by heuermh** [comment]
Closing as WontFix.  Neither STAR nor HISAT2 will work with Cannoli, as neither can handle interleaved FASTQ or unaligned BAM on standard input.
