### ISSUE TITLE
Single_end_reads

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/cannoli#125]
Hi @hammer 
Can Cannoli  work with single_end_reads?

I see Cannoli can work like this :   
SRR1517848_1.fastq
SRR1517848_2.fastq

Interleave with Cannoli : SRR1517848.fastq
then next processing like alignment works fine

Q: Can Cannoli works with only one file like SRR1517848_1.fastq ? It did'nt work for me.

**Comment by heuermh** [comment]
Hello @Rokshan2016!  Which command are you trying to use in Cannoli?

**Comment by Rokshan2016** [comment]
I used this command : 

 ./cannoli-submit interleaveFastq hdfs://ipsdevhdp/user/rokshan.jahan/bioinformatics_pipeline/raw_fastq_data/SRR1518011_1.fastq hdfs://ipsdevhdp/user/rokshan.jahan/bioinformatics_pipeline/raw_fastq_data/SRR1518011_2.fastq  hdfs://ipsdevhdp/user/rokshan.jahan/bioinformatics_pipeline/pair_end_reads/SRR1518011.fastq

And 
 ./cannoli-submit --driver-memory 3g --executor-memory 3g -- bwa -bwa_path /data01/genomics/adamproject/build_64/bwa-master/bwa hdfs://ipsdevhdp/user/rokshan.jahan/bioinformatics_pipeline/interleave_fastq/SRR1518011.fastq hdfs://ipsdevhdp/user/rokshan.jahan/bioinformatics_pipeline/SRR1518011canoli.adam SRR1518011 -index /data01/genomics/adamproject/human_g1k_v37/human_g1k_v37.fasta -sequence_dictionary hdfs://ipsdevhdp/user/rokshan.jahan/bioinformatics_pipeline/human_g1k_v37.dict -force_load_ifastq


Its working fine. 


But if I am trying to use one file without Interleave it is not working.

**Comment by heuermh** [comment]
@Rokshan2016 bwa via Cannoli doesn't support aligning single ended reads, because the reads are streamed to bwa over a pipe in interleaved FASTQ format.
