### ISSUE TITLE
Cannot read hdfs files

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/cannoli#136]
Can cannoli read hdfs files? I am trying to run bwa with a file on hdfs and I am getting a `No such file or directory` error on the input:

```
./bin/cannoli-submit \
        -- \
        bwa \
        hdfs:///<myfile>.bam \
        hdfs:///<myfile>.hg38.alignments.adam \
        <mysample> \
        -index hg38.fa \
        -sequence_dictionary hg38.dict \
        -fragments \
        use_docker \
        -image quay.io/ucsc_cgl/bwa:0.7.12--256539928ea162949d8a65ca5c79a72ef557ce7c \
        -add_indices
```

**Comment by heuermh** [comment]
What version of cannoli are you using?

`cannoli-submit` INPUT and OUTPUT arguments are just like `adam-submit`, so the `hdfs:///<myfile>.bam` and `hdfs:///<myfile>.hg38.alignments.bam` paths should be fine.

`-index` and `-sequence_dictionary` are more complicated, however, especially when invoked via Docker.  Where are those being read from?

**Comment by heuermh** [comment]
Also note the Docker image you are specifying is not appropriate for using Cannoli, as it doesn't put `bwa` on the path (it uses an ENTRYPOINT bash wrapper script).

```
$ docker run -it \
  quay.io/ucsc_cgl/bwa:0.7.12--256539928ea162949d8a65ca5c79a72ef557ce7c \
  bwa

[main] unrecognized command 'bwa'
```

```
$ docker run -it \
    quay.io/biocontainers/bwa:0.7.17--pl5.22.0_0 \
    bwa

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.17-r1188
Contact: Heng Li <lh3@sanger.ac.uk>

Usage:   bwa <command> [options]

Command: index         index sequences in the FASTA format
         mem           BWA-MEM algorithm
         fastmap       identify super-maximal exact matches
         pemerge       merge overlapping paired ends (EXPERIMENTAL)
         aln           gapped/ungapped alignment
         samse         generate alignment (single ended)
         sampe         generate alignment (paired ended)
         bwasw         BWA-SW for long queries

         shm           manage indices in shared memory
         fa2pac        convert FASTA to PAC format
         pac2bwt       generate BWT from PAC
         pac2bwtgen    alternative algorithm for generating BWT
         bwtupdate     update .bwt to the new format
         bwt2sa        generate SA from BWT and Occ

Note: To use BWA, you need to first index the genome with `bwa index'.
      There are three alignment algorithms in BWA: `mem', `bwasw', and
      `aln/samse/sampe'. If you are not sure which to use, try `bwa mem'
      first. Please `man ./bwa.1' for the manual.
```

For Cannoli we're using the Docker (and Singularity, by extension) images created by the BioContainers project, which in turn are created from Bioconda recipes.  That seems to be a community-wide standard for using Docker in workflows.

**Comment by akmorrow13** [comment]
Thanks @heuermh. I am using file:/mnt/fb/resources/GRCh38/hs38DH.bowtie2 for the extention, but it seems to not be able to find the index file. Does it have to be on hdfs?

**Comment by akmorrow13** [comment]
I am trying to run without docker, and have installed bwa on the master node. I logged into the other nodes and can successfull access bwa. However, the worker nodes are failing with  `Cannot run program "bwa": error=2, No such file or directory`

**Comment by heuermh** [comment]
If you're using git head, look for an INFO log line matching
`Piping {} to bwa with command: {} files: {}`.

**Comment by akmorrow13** [comment]
Here is the output on an example file:
` INFO cannoli.Bwa: Piping RDDBoundFragmentRDD with 66 reference sequences, 24 read groups, and 1 processing steps to bwa with command: [bwa, mem, -t, 1, -R, @RG\tID:mousy\tLB:mousy\tPL:ILLUMINA\tPU:0\tSM:mousy, -p, file:///.../hs38DH.fa.bwt, -] files: []`

It is failing because the worker nodes cannot find bwa. I assume this is because I (a lowely user) installed bwa and put it in my bashrc file, which Spark is running as root. Does this mean that the cluster needs to have bwa installed as root? Have you successfully ran cannoli on a Program that you installed?

**Comment by heuermh** [comment]
> Does this mean that the cluster needs to have bwa installed as root?

If bwa is installed in the same place on every node, you can provide the fully qualified local path with the `-executable` argument.  Or that argument could point to a bash script that found the right executable.

> Have you successfully ran cannoli on a Program that you installed?

Yes, locally and on AWS.  On the bdg cluster I've only tried things that were already installed or used Docker.

**Comment by akmorrow13** [comment]
I seem to get a re-occuring error org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory <myfile>.bam.adam already exists, even though it is created in the process

**Comment by akmorrow13** [comment]
Running without docker, and setting the -executable flag to the bwa installation worked.
