### ISSUE TITLE
BWA Fails with Output directory already exists for more than 1 executor

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/cannoli#137]
When bwa runs on more than 1 executor, it seems the output directory is attempted to be created multiple times. Fails with error:

```
User class threw exception: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory chr17.7500000-7515000.aligned.sam already exists
```

**Comment by akmorrow13** [comment]
`org.apache.hadoop.mapred.FileAlreadyExistsException` seems to be the issue that bubbles to the top. The real issue was that psshing in and memory mapping the bwa index did not work for a subset of the workers, so those workers were failing with an `index not found` error. However, I am not sure why this resulted in a `org.apache.hadoop.mapred.FileAlreadyExistsException` from the Hadoop application page.

**Comment by heuermh** [comment]
Could it be that when the failed nodes retried they were allocated the same region of the genome as already running on another node?  Is this an issue for Cannoli?

**Comment by heuermh** [comment]
I'm closing this as not an issue with Cannoli -- please reopen if you would like.
