### ISSUE TITLE
Add ability to force load format for BWA

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/cannoli#14]
I'm running on a BZip2 compressed interleaved FASTQ. Since the extension is .bz2, the automagical loader (https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L1582) doesn't pick up that the file is interleaved FASTQ. We should add switches (as we have in [Transform](https://github.com/bigdatagenomics/adam/blob/master/adam-cli/src/main/scala/org/bdgenomics/adam/cli/Transform.scala#L88-L94)) to force the input file format.

**Comment by heuermh** [comment]
Shouldn't this be a new feature in adam?  I didn't think we could read gzipped or BZip2 compressed FASTQ (or FASTA, or feature) files.
