### ISSUE TITLE
Support Gem mapper in Cannoli

### ISSUE THREAD

**Issue by benraha** [bigdatagenomics/cannoli#170]
Hi,

I'm working with Prof. Eran Segal lab in the Weizmann institute, and we're interested of running Cannoli using the GEM mapper, and not BowTie or the others supported.

Has this thing been done ? I'd love to help and create a PR with some guidance.

Thanks,
Ben

**Comment by heuermh** [comment]
Hello @benraha!

I’m not familiar with GEM; if it does reasonable things with stdin and stdout then adding support in Cannoli is fairly straightforward.

**Comment by benraha** [comment]
Hi!

Thanks for the quick response:)

I'll have a look and see if I can make it work.

Ben

**Comment by heuermh** [comment]
Great!  Best case would be that it accepts unaligned BAM or interleaved FASTQ on stdin and writes aligned BAM to stdout.

**Comment by heuermh** [comment]
Checking back in to see if you've made any progress.

From https://github.com/smarco/gem3-mapper it appears that stdin and stdout are handled reasonably
```
./bin/gem-mapper \
  -I hsapiens_v37.gem \
  -i sample.Illumina.pe.fastq \
  -p \
  -o sample.Illumina.pe.sam

...

    -i, --input=FILE
      Input FASTA/FASTQ file [default=stdin]
      For Single-End mode and Paired-end if the FASTA/FASTQ 
      file contains read/1 and read/2 interleaved
...

    -o, --output=FILE
      Output file [default=stdout]
```

I can whip up a minimal version for Cannoli fairly quickly, how about I do that and then you provide feedback on the pull request?

**Comment by heuermh** [comment]
Thank you for the suggestion, @benraha!
