### ISSUE TITLE
Use Bowtie2 with single end reads

### ISSUE THREAD

**Issue by benraha** [bigdatagenomics/cannoli#186]
Hi!

Currently, running a command like Bowtie2 on FragmentDataset that was created from single end fastq files would not work, because of two reasons I see :

1. The call to Bowtie2 always uses "--interleaved", and I don't have enough knowledge to tell how it affects bowtie2 that it receives two non-related reads and thinks that they belong together.

2. Since the output is parsed using InterleavedFASTQInFormatter, all of the outputs will be filtered, since this formatter checks that each fragment contains exactly two alignments.

From my understanding, this is not a necessity of Bowtie2, but rather a design decision by cannoli, to only work with interleaved files.

Is there a way around that with the current design?

Thanks in advance,
Ben

**Comment by benraha** [comment]
Thanks for the quick response :)

I don't think I mind feeding it Fragments (containing a single read), so maybe only adding a param, and when it's given don't use --interleaved, and feed it to a more forgiving formatter ?

**Comment by heuermh** [comment]
I have added a single-end read bowtie2 function `AlignmentRecord` &rarr; `AlignmentRecord` in #187, this works from the `cannoli-submit` shell.  Do you also need a command line class?

**Comment by benraha** [comment]
For me it should be enough, thanks a lot !

**Comment by heuermh** [comment]
Thank you, @benraha 

I added a cli class and merged #187.
