### ISSUE TITLE
running tools with Conda

### ISSUE THREAD

**Issue by ypriverol** [bigdatagenomics/cannoli#206]
I saw that cannoli can use Singularity and Docker. Any future plans to use Conda? 

Regards 
Yasset

**Comment by heuermh** [comment]
Hello @ypriverol, thank you for submitting this issue!

I am not sure what it would mean to use Conda to run tools via Cannoli.  Cannoli needs to modify the command line used to call a tool via Docker or Singularity (e.g. `docker run ... -it bwa` vs `bwa` if installed locally to each executor node).

One could use Conda separately to install tools to each executor node, or is there some wrapper script one calls to do this on the fly?

**Comment by heuermh** [comment]
Ping @ypriverol, I am still hoping for clarification.

**Comment by heuermh** [comment]
Closing this for now, pending further discussion
