### ISSUE TITLE
Scala 2.12 / spark 2.4.4 release

### ISSUE THREAD

**Issue by jamesthegiantpeach** [bigdatagenomics/cannoli#215]
I am looking get a release of this for scala 2.12. Do you know LOE here?

**Comment by heuermh** [comment]
We have cross-Spark and -Scala build configuration support in the Cannoli build but it is not currently enabled.  We should reenable it for Scala 2.12 and prepare for the upcoming Spark 3 release.

**Comment by jamesthegiantpeach** [comment]
Ok sounds good. Friday I configured a 2.12 build that failed. Looks like you've already got a pr in the works for this though

**Comment by heuermh** [comment]
Scala 2.12 uses Java 8-style lambdas for functions and that breaks some of our APIs at compile time, requiring the use of casts.  When we no longer have to support Scala 2.11, we can drop those Java-friendly methods causing trouble under Scala 2.12+.

**Comment by heuermh** [comment]
Scala 2.12 artifacts are now available in the [Sonatype snapshots repository](https://oss.sonatype.org/content/repositories/snapshots/org/bdgenomics/cannoli/), e.g.
```xml
<dependency>
  <groupId>org.bdgenomics.cannoli</groupId>
  <artifactId>cannoli-core-spark2_2.12</artifactId>
  <version>0.9.0-SNAPSHOT</version>
</dependency>
```

**Comment by jamesthegiantpeach** [comment]
Rad. I have some special snowflake settings on my spark build. Can I build this against my spark build via setting spark.version=2.12 when running mvn install?
