### ISSUE TITLE
blastn db not support HDFS?

### ISSUE THREAD

**Issue by yvanst** [bigdatagenomics/cannoli#224]
Hi, firstly I want to thank you for your developing this project, it's a great work.
but I got into some problems that I think you may help me out.
I use this command to run blast
```bash
cannoli-submit \
    -- \
    blastn \
    -db hdfs://my-aws-emr/user/hadoop/uncompressed_nt/  \
    hdfs://my-aws-emr/user/hadoop/query.fa \
    ./result.sam
```
but got errors below
```
Caused by: java.lang.RuntimeException: Piped command List(blastn, -db, /user/hadoop/uncompressed_nt, -outfmt, 17 SR SQ, -parse_deflines) exited with error code 2.
```

It seems to me that the -db option direct to a wrong path, can -db option support HDFS or S3? or it can only use local files?

in my opinion, db normally is too large(nt is 70GB+), it's better to put it on HDFS to avoid having a replica on every compute machine, what do you think of it?

is there a proper solution?

**Comment by yvanst** [comment]
@heuermh Thank you for your reply, it helps a lot, I'll try what you mentioned

**Comment by yvanst** [comment]
Hello @heuermh , I'm following your advice using NFS to share files, but I got another problem.

It turns out I misunderstood the -db option previously, according to [ncbi](https://www.ncbi.nlm.nih.gov/books/NBK52640/), I should set the BLASTDB environment variable to the database path(in my case, /home/hadoop/efs), and use -db to specify the database name(in my case nt).

Here is what it looks like in my case
``` bash
ls efs
# nt.00.nhd  nt.10.nsi  nt.21.nog ...
```
and I can run it using blastn
``` bash
blastn -query query.fa -db nt -num_threads 16 -out output.sam
```
but when I run cannoli
```bash
cannoli-submit \
    -- \
    blastn \
    -db nt \
    -single  \
    hdfs://my-aws-emr/user/hadoop/query.fa \
    hdfs://my-aws-emr/user/hadoop/output.sam
```
I got the errors below
```
2020-02-01 09:31:42 ERROR Blastn:128 - BLAST database nt not found, touch an empty file at this path if it does not exist
Command body threw exception:
java.io.FileNotFoundException: File nt does not exist
2020-02-01 09:31:42 INFO  Blastn:159 - Overall Duration: 4.84 secs
Exception in thread "main" java.io.FileNotFoundException: File nt does not exist
```
I think maybe cannoli misunderstood the db option, cause the db option didn't indicate a file, but a database name and a lot of files(e.g., nt.00.nhd..)
what do you think of it?

**Comment by heuermh** [comment]
Ah, we have run into that before https://github.com/bigdatagenomics/cannoli/issues/177#issuecomment-517964778

The workaround would be to touch `/home/hadoop/efs/nt` to create an empty file at that path.

**Comment by yvanst** [comment]
Hello @heuermh , touching an empty file solves the previous problem and my application can start, but shortly after I encounter another error.

``` bash
cannoli-submit \
    -- \
    blastn \
    -db nt \
    -single  \
    s3://my-s3/queries/small_queries.fa \
    s3://my-s3/results/output.sam
```
and here is the errors
```
...
20/02/02 08:46:06 INFO BlockManagerInfo: Added broadcast_3_piece0 in memory on ip-172-31-32-105.ap-northeast-1.compute.internal:35789 (size: 10.2 KB, free: 5.9 GB)
20/02/02 08:46:06 INFO SparkContext: Created broadcast 3 from broadcast at FastaConverters.scala:181
20/02/02 08:46:06 ERROR Blastn: BLAST database nt not found, touch an empty file at this path if it does not exist
Command body threw exception:
java.io.FileNotFoundException: File does not exist: hdfs://ip-172-31-32-105.ap-northeast-1.compute.internal:8020/user/hadoop/nt
20/02/02 08:46:06 INFO Blastn: Overall Duration: 18.14 secs
Exception in thread "main" java.io.FileNotFoundException: File does not exist: hdfs://ip-172-31-32-105.ap-northeast-1.compute.internal:8020/user/hadoop/nt
	at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1444)
	at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1437)
```
same as before, I use NFS to share database(`export BLASTDB=/home/hadoop/efs`), I don't know somehow the program use a wrong file path.

and add another empty nt file in HDFS can bypass the check, but I think you should solve it.

p.s.
I have one more question, I did not see any support for `-num_threads` option in blastn. 
and according to this [discussion](https://www.biostars.org/p/119614/), the best practice is to set one core per executor, isn't it?

**Comment by heuermh** [comment]
By default, Hadoop file system relative paths without a scheme will assume `hdfs://` in the current user's HDFS home directory, that is why it is looking for `hdfs://ip-172-31-32-105.ap-northeast-1.compute.internal:8020/user/hadoop/nt`.

Note also that exporting `BLASTDB=...` won't work unless you do the same on all executor nodes.

Thus for a blast database path on NFS, I think you want to use either the absolute path `/home/hadoop/efs/nt` or a file URL `file:///home/hadoop/efs/nt`.

With regards to `-num_threads`, if necessary we can add that to the Cannoli BlastnArgs class and raise it to the command line interface.

Meanwhile, you could use `CommandBuilder` directly to do something like this in `cannoli-shell`
```scala
val builder = CommandBuilders.create(useDocker = false, useSingularity = false)
  .setExecutable("blastn")
  .add("-db")
  .add("/home/hadoop/efs/nt")
  .add("-outfmt")
  .add("17 SR SQ")
  .add("-parse_deflines")
  .add("-num_threads")
  .add("1")

implicit val tFormatter = FASTAInFormatter
implicit val uFormatter = new AnySAMOutFormatter(ValidationStringency.STRICT)

val alignments: AlignmentDataset = sequences.pipe[Alignment, AlignmentProduct, AlignmentDataset, FASTAInFormatter](
  cmd = builder.build(),
  files = builder.getFiles()
)
```
(The main point of Cannoli is to hide the details of this ADAM `pipe` API from the user, but it isn't that difficult to use directly)

**Comment by yvanst** [comment]
Thank you, @heuermh 
I closed this issue as my case could work finally, and I wrote down this as a note.

I changed the code a little bit to suit my case, but I kept encountering one error as `Job aborted due to stage failure... Exception from container-launch.` , after days of trying, I finally realized that the process spawned from the executor does not have the environment variables I set in the ~/.bashrc

in this case, add an `environment` parameter in the `pipe` function should work

**Comment by heuermh** [comment]
The `pipe` API does support an `environment` parameter
https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicDataset.scala#L786

To clarify, did you mean that you were able to use this method to solve your issue?

**Comment by heuermh** [comment]
And thank you for mentioning the bowtie2 issue, I've created issue https://github.com/bigdatagenomics/cannoli/issues/228 and will work with the bioconda folks to create a docker build for bowtie2 version 2.3.5.1.

**Comment by yvanst** [comment]
yes, if you want to use some environment variables in this command(e.g., BLASTDB, BOWTIE2_INDEXES) and use -db option only as database name, it won't work if you put that environment variable in ~/.bashrc, you need to use the `environment` parameter in `pipe` command

although one workaround is to use the full path as  `-db file:///home/hadoop/efs/blast/nt`

**Comment by heuermh** [comment]
Thanks for the clarification!  We could push `environment` capture up to the Cannoli API but I don't know the best way to specify environment variables on the command line.  Should `cannoli-submit` gather those in its environment and pass them along?  Or should the user specify key-value pairs as a single `--environment` argument?

**Comment by yvanst** [comment]
both should be  fine, I think explicitly adding the argument as cannoli options is easier to implement and to debug.
since HDFS is not support in the `-db` option, I think maybe we could remove the `absolute()` method when calling.(it could only be file://, isn't it?)
if environment variable is supported, I think we can use a more unified way that resemble to the original one to call the command(we can also remove fastfail to avoid touch an empty file)
what do you think of it?
