### ISSUE TITLE
blastn ouput FileAlreadyExistsException

### ISSUE THREAD

**Issue by yvanst** [bigdatagenomics/cannoli#225]
Hello, I'm using this command to run cannoli with blast
```bash
cannoli-submit \
    --master yarn \
    --deploy-mode cluster \
    --executor-cores 1 \
    --executor-memory 2g \
    -- \
    blastn \
    -executable $HOME/conda/bin/blastn \
    -db nt \
    s3://my-s3-bucket/queries/query.fa \
    s3://my-s3-bucket/results/output.sam

```
but got errors below
```
20/02/02 11:11:22 ERROR Client: Application diagnostics message: User class threw exception: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory s3://my-s3-bucket/results/output.sam already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:146)
	at org.apache.spark.rdd.InstrumentedOutputFormat.checkOutputSpecs(InstrumentedOutputFormat.scala:38)
        ...
```

Here is what it looks like in s3
```bash
 ~ aws s3 ls s3://my-s3-bucket/results/ --recursive
2020-01-30 14:15:21          0 results/
2020-02-02 19:11:05         23 results/output.sam/part-r-00000.sam
2020-02-02 19:11:05         23 results/output.sam/part-r-00011.sam
2020-02-02 19:11:05         23 results/output.sam/part-r-00021.sam
2020-02-02 19:11:05         23 results/output.sam/part-r-00024.sam
2020-02-02 19:15:03         23 results/output.sam_head
```
and when I use `-single` option, the error would be `Output directory s3://my-s3-bucket/results/output.sam_tail already exists`.
Can you fix this?

**Comment by yvanst** [comment]
ping @heuermh ...

**Comment by heuermh** [comment]
I don't believe I've run into this before, because typically on EMR I write to HDFS and then use [Conductor](https://github.com/BD2KGenomics/conductor) or `s3-dist-cp` to move to s3.

This might be an ADAM bug, in that the `.sam_head`/`.sam_tail` temporary files should be unique per-executor.

**Comment by yvanst** [comment]
s3 should work, as #https://github.com/bigdatagenomics/cannoli/issues/137 mentioned, other problem leads to this

**Comment by heuermh** [comment]
Sorry, I am not sure what you mean by the last comment.  Is this still an issue for your workflow?

**Comment by yvanst** [comment]
after I solved other problem, this gone either, although I don't know why. but there is weird names in S3 as `output_$folder$`
