### ISSUE TITLE
java.lang.UnsupportedOperationException: empty.max while sorting and indexing.

### ISSUE THREAD

**Issue by Arun-George-Zachariah** [bigdatagenomics/cannoli#237]
Hi,

I get the below error while trying to sort and index.

```
java.lang.UnsupportedOperationException: empty.max
  at scala.collection.TraversableOnce$class.max(TraversableOnce.scala:229)
  at scala.collection.AbstractTraversable.max(Traversable.scala:104)
  at org.bdgenomics.adam.rdd.read.AlignmentDataset$$anonfun$sortByReferencePositionAndIndex$1.apply(AlignmentDataset.scala:1036)
  at org.bdgenomics.adam.rdd.read.AlignmentDataset$$anonfun$sortByReferencePositionAndIndex$1.apply(AlignmentDataset.scala:1028)
  at scala.Option.fold(Option.scala:158)
  at org.apache.spark.rdd.Timer.time(Timer.scala:48)
  at org.bdgenomics.adam.rdd.read.AlignmentDataset.sortByReferencePositionAndIndex(AlignmentDataset.scala:1028)
  ... 53 elided
```

The code executed:
```
import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.cannoli.Cannoli._
import org.bdgenomics.cannoli.cli.BwaArgs

val sample_1_path = "hdfs://vm0:9000/SRR062635_1.filt.fastq"
val sample_2_path = "hdfs://vm0:9000/SRR062635_2.filt.fastq"
val reference = "hdfs://vm0:9000/hs38.fa"

val reads = sc.loadPairedFastqAsFragments(sample_1_path, sample_2_path)

val bwaArgs = new BwaArgs()
bwaArgs.sampleId = "SRR062635"
bwaArgs.indexPath = reference
bwaArgs.executable = "/mydata/bwa/bwa"

val alignments = reads.alignWithBwa(bwaArgs)

val sorted = alignments.sortByReferencePositionAndIndex()
```
How do I go about this issue?

**Comment by heuermh** [comment]
I don't believe `bwa` can use a reference stored on `hdfs`.  There may be some messages in the log files pertaining to this.

For an indexed reference genome on a cluster, you can either store it at the same local path on each executor node or use [Spark to copy the reference to a temporary location on each executor node](https://github.com/bigdatagenomics/cannoli/blob/master/core/src/main/scala/org/bdgenomics/cannoli/Bwa.scala#L48).  For the latter, use `bwaArgs.addFiles = true`.

**Comment by Arun-George-Zachariah** [comment]
You are right! `bwa` cannot use a reference stored on HDFS. But I get the same error even when I have a copy of reference indexes on the executor nodes. 

The error here is because the sequence dictionary formed is empty. If I load an external sequence dictionary using `sc.loadSequenceDictionary` and replace the sequence dictionary of the `alignments` object, `sortByReferencePositionAndIndex` works without any issue.

**Comment by heuermh** [comment]
Ah yes, I have run into this before!  The command line version of Cannoli `bwa` provides a sequence dictionary argument and replaces the sequence dictionary here

https://github.com/bigdatagenomics/cannoli/blob/master/cli/src/main/scala/org/bdgenomics/cannoli/cli/Bwa.scala#L103

so if you are running in `cannoli-shell` and starting from FASTQ sequences, an external sequence dictionary must be loaded, as you have found.  Something to be added to docs certainly!

**Comment by Arun-George-Zachariah** [comment]
Thanks for the clarification.  

Yes, the documents definitely need to be updated. It will help in the wider adoption of the framework.

**Comment by heuermh** [comment]
Note this issue when writing docs for #91.
