### ISSUE TITLE
Freebayes CLI command writes to wrong path

### ISSUE THREAD

**Issue by yvanst** [bigdatagenomics/cannoli#239]
Hello, I think you maybe made a typo here, which should be args.outputPath

https://github.com/bigdatagenomics/cannoli/blob/99338f71d0069c15834f9dbbf4b0022206d329ab/cli/src/main/scala/org/bdgenomics/cannoli/cli/Freebayes.scala#L78

**Comment by heuermh** [comment]
Ah, good catch!  I do most of my functional testing in `cannoli-shell` rather than from the command line.  It would be nice to run functional tests in CI, but I fear there would be too many Docker images to pull down.
