### ISSUE TITLE
force evaluating accumulators before assigning them

### ISSUE THREAD

**Issue by yvanst** [bigdatagenomics/cannoli#243]
Hello, 

in the situation below, I think you need to force the evaluation happen before `replaceHeaderLines`.
https://github.com/bigdatagenomics/cannoli/blob/8c04693b3cd51004578151c2bfa4fc005951a9df/core/src/main/scala/org/bdgenomics/cannoli/Freebayes.scala#L108-L119
for example, you can add `variantContexts.rdd.count()` at line 117. though I didn't run the freebayes code.

**Comment by heuermh** [comment]
Hello @yvanst, thanks for the suggestion!

I know that Spark accumulators can be quite unreliable; I don't think I've run into a problem here though.  Perhaps it might be better to not use accumulators at all for this use case (which is to capture the headers streamed out from e.g. `freebayes` and merge them with the ones ADAM expects to see).

**Comment by yvanst** [comment]
okay, I didn't test freebayes, just let you know that if you encounter empty headers, it might be that reason.

**Comment by heuermh** [comment]
Fixed by #273
