### ISSUE TITLE
Unable to find bowtie2 index from hdfs

### ISSUE THREAD

**Issue by drees1** [bigdatagenomics/cannoli#246]
Hello,

I am trying to configure and run a basic cluster running bowtie2 on a set of .fastq reads piped through cannoli, and saving the output as .sam, but am struggling to configure and debug the program correctly.  

When I run my script referencing local filepaths and deploying the spark shell locally, everything works as expected.  Following previous issues, I need to touch an empty file at path/to/reference.fa so that bowtie2 recognizes the reference index files. 

When I change the reference and read files to hdfs files on my cluster (still using local spark) the program fails to find the reference index.  
```
scala> alignments.saveAsSam("hdfs://[EC2PUBLICDNS]:9000/user/ubuntu/results/reads.aligned.sam",asSingleFile=true)
(ERR): "/user/ubuntu/index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index" does not exist or is not a Bowtie 2 index
Exiting now ...
```
I can import the unaligned_reads.fastq file from hdfs as an rdd, and I can write the unaligned file in .sam format to hdfs, so I do not suspect that this is an issue with my hdfs configuration or url syntax.

I can confirm that the reference files exist at the hdfs path, and that the empty .fa file also exists.  You'll see that i have tried empty files with extensions .fa, .fna, and no extension with no success:
```
$ hadoop fs -ls index
-rw-r--r--   3 ubuntu supergroup          0 2020-06-19 23:12 index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index
-rw-r--r--   3 ubuntu supergroup  982525150 2020-06-19 23:12 index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.1.bt2
-rw-r--r--   3 ubuntu supergroup  733719120 2020-06-19 23:12 index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.2.bt2
-rw-r--r--   3 ubuntu supergroup      10880 2020-06-19 23:12 index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.3.bt2
-rw-r--r--   3 ubuntu supergroup  733719113 2020-06-19 23:12 index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.4.bt2
-rw-r--r--   3 ubuntu supergroup          0 2020-06-19 23:12 index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.fa
-rw-r--r--   3 ubuntu supergroup          0 2020-06-19 23:12 index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.fna
-rw-r--r--   3 ubuntu supergroup  982525150 2020-06-19 23:12 index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.rev.1.bt2
-rw-r--r--   3 ubuntu supergroup  733719120 2020-06-19 23:12 index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.rev.2.bt2
```
The index path is set to:
```
scala> args.indexPath = "hdfs://[EC2PUBLICDNS]:9000/user/ubuntu/index/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index"
```
Any guidance that you could offer on this issue would be greatly appreciated.  I'd like to learn how to utilize the tools that your team is developing more effectively.

**Comment by heuermh** [comment]
Hello @drees1, thank you for reporting this issue!

Spark of course can read from and write to HDFS but `bowtie2` cannot.  To make reference files available to the `bowtie2` process there are a few options, and possibly others:

 * Install the reference to every cluster node at the same local path, e.g. `/local/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index`

 * Make the reference available to every cluster node via shared disk, e.g. NFS `/shared/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index`

 * Use the Spark files mechanism to copy the reference to local temporary disk on each cluster node, i.e. `-add_files -index /local-to-spark-driver-node/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index` or `-add_files -index hdfs:///GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index`

 * Bake the reference into a Docker or Singularity image with `bowtie2` executable, and use a reference path local to the container image, e.g. `-use-docker -image bowtie2-docker-image -index /docker/local/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index`

There will be a network hit one way or another, unfortunately it is kind of unavoidable.  Please let me know if any of these seem like a good fit for your cluster environment.

**Comment by drees1** [comment]
I knew that the fix was bound to be as simple as a single line of code.  With ```bowtieArgs.addFiles = true``` it runs as expected.  Thank you for your prompt reply.

**Comment by heuermh** [comment]
No problem, thanks again!
