### ISSUE TITLE
Bump BWA docker version argument

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/cannoli#27]
The current docker container we point at encounters [this known BWA/zlib version incompatibility](https://sourceforge.net/p/bio-bwa/mailman/message/31573132/). https://github.com/BD2KGenomics/cgl-docker-lib/pull/241 contains a commit that will resolve this issue.

**Comment by heuermh** [comment]
The [bwa image on BioContainers](https://biocontainers.pro/registry/#/showImages?domain=quay&repository=bwa&starred=false&modified=08%2F11%2F2017) was last built 11 Aug 2017, would that still have this issue?  See #92.

**Comment by heuermh** [comment]
Fixed by #96.
