### ISSUE TITLE
Factor out docker/mapping code

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/cannoli#34]
In #25 we add the ability to run BWA through Docker, and to mount reference files locally on the executors. We should factor this code out from BWA into a general pattern that we can use across all of the tools in `cannoli`.

It should support the matrix of:

* Running tools natively or running tools from a docker container
* Mounting index files local to the executor, mounting index files into the docker container, or not doing anything (i.e., index/ref files are on a globally mounted file system)

**Comment by heuermh** [comment]
@fnothaft is git head the latest you've been using for BWA in cannoli?  I need to better grok what is going on with all the path munging so that I can flesh out pull request #54.

**Comment by heuermh** [comment]
Fixed by #107.
