### ISSUE TITLE
support for MACS2 or other peak calling

### ISSUE THREAD

**Issue by akmorrow13** [bigdatagenomics/cannoli#35]
@heuermh would you be ok with putting some peak calling functionality in here? @gunjanbaid
and I are about implementing MACS2 for peak calling

**Comment by heuermh** [comment]
+1, the more the merrier.  If it gets too nuts, we might want to break up the list of tools into category command groups in `Cannoli.scala`, alignment, variant calling, etc.

**Comment by heuermh** [comment]
Closing as WontFix
