### ISSUE TITLE
Interleaver should support uBAM

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/cannoli#39]

**Comment by heuermh** [comment]
uBAM?  I hope that is a typo.

**Comment by fnothaft** [comment]
Not a typo.

**Comment by heuermh** [comment]
Have a reference link then?  I'd like to throw a shoe at someone.

**Comment by fnothaft** [comment]
uBAM = unaligned BAM?

**Comment by heuermh** [comment]
Ah ok.  I thought there was a new micro-BAM format or some such nonsense.  :)
