### ISSUE TITLE
 BCF not yet supported 

### ISSUE THREAD

**Issue by shibuvp** [bigdatagenomics/cannoli#44]
i'm getting following error while running freebayes using cannoli
my command -------
ADAM_MAIN=org.bdgenomics.cannoli.Cannoli adam-submit --jars /opt/cannoli/target/cannoli_2.10-0.1-SNAPSHOT.jar -- freebayes -freebayes_reference hdfs://master.hdp:8020/Data/HumanBase/hg19/hg19.fa hdfs://master.hdp:8020/opt/small5.adam hdfs://master.hdp:8020/opt/sample.genotypes.adam
the error ------ Exception in thread "main" java.lang.AssertionError: assertion failed: BCF not yet supported

![cannoli-assertion failed-bcf not yet supported](https://user-images.githubusercontent.com/25296847/27325621-aa86e174-55c6-11e7-869f-f4dab2361365.JPG)

**Comment by heuermh** [comment]
Ah, sorry, the example I gave on gitter is incorrect.

As of the current version of Cannoli, `freebayes` only supports writing out as VCF.
https://github.com/bigdatagenomics/cannoli/blob/master/src/main/scala/org/bdgenomics/cannoli/Freebayes.scala#L106

```
$ ADAM_MAIN=org.bdgenomics.cannoli.Cannoli \
  adam-submit \
  --jars /opt/cannoli/target/cannoli_2.10-0.1-SNAPSHOT.jar \
  -- \
  freebayes \
  -freebayes_reference hdfs://master.hdp:8020/Data/HumanBase/hg19/hg19.fa \
  hdfs://master.hdp:8020/opt/small5.adam \
  hdfs://master.hdp:8020/opt/sample.vcf
```

**Comment by shibuvp** [comment]
okay

**Comment by shibuvp** [comment]
i have used the above command you posted, but i'm  getting this error

htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file
![cannoli2](https://user-images.githubusercontent.com/25296847/27369780-220d2d1a-5677-11e7-91b5-fc1548de4948.JPG)

**Comment by heuermh** [comment]
I believe the tribble exception may be misleading. The `could not open hdfs://master.hdp:8020/Data/HumanBase/hg19/hg19.fa` is likely more relevant.
```bash
$ freebayes -f does-not-exist.fa
Please specify a BAM file or files.

$ echo $?
1
```

**Comment by shibuvp** [comment]
when i use --  freebayes -f hdfs://master.hdp:8020/Data/HumanBase/hg19/hg19.fa , shows that 
"-f" is not a valid option, but i can find -f in --help (freebayes --help in cannoli), i think -f option not work in freebayes in cannoli.
 moreover i never have a bam file , i'm looking in a way that using adam file.
![cannoli3](https://user-images.githubusercontent.com/25296847/27420051-c3a4de6e-5741-11e7-8704-c779c7ee0019.JPG)

**Comment by heuermh** [comment]
There is no `-f` in freebayes in cannoli, it should be `-freebayes_reference VAL`.
This maps to `-f` when cannoli calls freebayes externally via the pipe API.

**Comment by shibuvp** [comment]
Hmmm oke...i tried out again with the following command , but the error is the same!
`ADAM_MAIN=org.bdgenomics.cannoli.Cannoli adam-submit  --jars /opt/cannoli/target/cannoli_2.10-0.1-SNAPSHOT.jar -- freebayes -freebayes_reference hdfs://master.hdp:8020/Data/HumanBase/hg19/hg19.fa   hdfs://master.hdp:8020/opt/small5.adam   hdfs://master.hdp:8020/opt/sample91.vcf`

and getting output as two files, that is 
0 sized .vcf file and vcf_head file 
![cannoli4](https://user-images.githubusercontent.com/25296847/27467166-a069b778-57fd-11e7-9fde-557064a6d6ce.JPG)

header file contains header info only. how should i get ride of this issue?

**Comment by a1xt06** [comment]
What is the error?

**Comment by shibuvp** [comment]
i'm getting the following error 

htsjdk.tribble.TribbleException$InvalidHeader: Your input file has a malformed header: We never saw the required CHROM header line (starting with one #) for the input VCF file
![cannoli5](https://user-images.githubusercontent.com/25296847/27720311-889a2776-5d76-11e7-8370-b341db9f0c8e.JPG)

**Comment by a1xt06** [comment]
Let's start from the beginning, What was the command you input?

**Comment by shibuvp** [comment]
i had used this command  
` ADAM_MAIN=org.bdgenomics.cannoli.Cannoli adam-submit  --jars /opt/cannoli/target/cannoli_2.10-0.1-SNAPSHOT.jar -- freebayes -freebayes_reference hdfs://master.hdp:8020/Data/HumanBase/hg19/hg19.fa   hdfs://master.hdp:8020/sample/salim3.adam   hdfs://master.hdp:8020/vcfoutput/sample206.vcf`

**Comment by a1xt06** [comment]
I'm not sure if a reference on hdfs will work. Could you try using the test reference and see what happens?

**Comment by heuermh** [comment]
Right, the `-freebayes_reference` argument value `hdfs://master.hdp:8020/Data/HumanBase/hg19/hg19.fa` is passed to the `freebayes` executable, which likely doesn't know how to deal with `hdfs://` scheme URLs.

**Comment by shibuvp** [comment]
okey. i was trying to access reference genome from locally on cluster , not from hdfs. 
` ADAM_MAIN=org.bdgenomics.cannoli.Cannoli adam-submit  --jars /opt/cannoli/target/cannoli_2.10-0.1-SNAPSHOT.jar -- freebayes -freebayes_reference /opt/artificial.fa   hdfs://master.hdp:8020/sample/salim3.adam  -single  hdfs://master.hdp:8020/vcfoutput/sample217.vcf`

here 

> artificial.fa is size of 1.15kb  

i got this  reference genome from adam resources and now i could see this error



![cannoli6](https://user-images.githubusercontent.com/25296847/27780558-43d9397e-5fe7-11e7-9749-3b94832b9cea.JPG)

the job doesn't completes

getting this output when i was abort the job.



![cannoli8](https://user-images.githubusercontent.com/25296847/27780868-0bdd1ef8-5fe9-11e7-8be2-f26ec0803249.JPG)
![cannoli7](https://user-images.githubusercontent.com/25296847/27780880-1d395676-5fe9-11e7-93eb-d4d59802c361.JPG)

**Comment by fnothaft** [comment]
@heuermh we should add the ability to use references stored in HDFS. I think this is a separate issue from what's been discussed here, so I've added #50 to track this.

**Comment by a1xt06** [comment]
Can you try without the "single" flag?

**Comment by shibuvp** [comment]
ya sure

**Comment by shibuvp** [comment]
@a1xt06   getting this output when i was trying without the "single" flag
![cannoli9](https://user-images.githubusercontent.com/25296847/27894871-8e02a5b6-622c-11e7-97e0-3189edbbc0cd.JPG)
and the command which i used to run

` ADAM_MAIN=org.bdgenomics.cannoli.Cannoli adam-submit  --jars /opt/cannoli/target/cannoli_2.10-0.1-SNAPSHOT.jar -- freebayes -freebayes_reference file:///Data/HumanBase/hg19/hg19.fa  hdfs://master.hdp:8020/sample/salim3.adam   hdfs://master.hdp:8020/vcfoutput/sample229.vcf`

also the error is still same as we discussed earlier

![cannoli10](https://user-images.githubusercontent.com/25296847/27895054-855d0fe0-622d-11e7-909a-30d92abbda22.JPG)

**Comment by heuermh** [comment]
@shibuvp Freebayes is complaining that it cannot open your reference file.  `could not open file:///Data/HumanBase/hg19/hg19.fa`

The error above looks to be due to missing or invalid RecordGroups in the original input BAM file. `NoSuchElementException: key not found: NewFile`

Perhaps it would be worthwhile to try running `freebayes` directly on a single node with your data.

```bash
$ freebayes -f hg19.fa salim3.bam > salim3.vcf 
```

Then if that succeeds, try running the same via Cannoli.

**Comment by shibuvp** [comment]
ok @heuermh i w'll try

**Comment by shibuvp** [comment]
and the issue is , i'm trying to using adam file rather than bam , is it possible in freebyes?

**Comment by heuermh** [comment]
Sorry for not following up sooner.  Freebayes itself can only run on BAM/SAM files.  Please reopen this issue if we can help further.
