### ISSUE TITLE
Move adam-cli to provided scope

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/cannoli#46]
Currently, we are setting [`adam-cli` to compile scope](https://github.com/bigdatagenomics/cannoli/blob/master/pom.xml#L376-L380). As long as we are depending on [`adam-submit` to submit cannoli jobs](https://github.com/bigdatagenomics/cannoli#running-cannoli-using-adam-submit), we should move `adam-cli` to provided scope.

**Comment by heuermh** [comment]
Nearly all the pull requests open here need a bump to adam version `0.23.0-SNAPSHOT`.  I'd like to do that and this in new pull requests, but they will get stuck on https://github.com/bigdatagenomics/adam/issues/1578.
