### ISSUE TITLE
Support loading reference files from HDFS/other file system

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/cannoli#50]
This is supported as part of the ADAM pipe transform using the optional `files` parameter, which copies files from a "global" path into local temp space on each Spark executor.

**Comment by heuermh** [comment]
So what needs to be done for this issue?  The `files` parameter in the pipe API is available for every Cannoli cli class to call, do we simply need to add a command line argument flag to add reference file(s) to `files`?  Such already exists in https://github.com/bigdatagenomics/cannoli/blob/master/cli/src/main/scala/org/bdgenomics/cannoli/cli/Bwa.scala#L91

**Comment by heuermh** [comment]
Fixed by #107.
