### ISSUE TITLE
Rename FastqInterleaver --> InterleaveFastq

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/cannoli#51]
Most of the ADAM commands are verb + plural noun.

**Comment by fnothaft** [comment]
Ah, but is (are?) "Fastq" parallel? :-p

**Comment by heuermh** [comment]
Yeah, I don't know.  I think I use fastq as plural.  At least, I've never thought or said "fastqs". It could be reads, I suppose, since we support writing to unaligned BAM files.
