### ISSUE TITLE
Add SNAP aligner

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/cannoli#65]
And deprecate https://github.com/bigdatagenomics/snappea.

**Comment by heuermh** [comment]
+1

I found

https://github.com/fnothaft/toil-bdg/blob/issues/15-benchmarking-pipelines/src/toil_bdg/benchmarking/single_node/align_and_call.py#L224

https://github.com/fnothaft/toil-bdg/blob/issues/15-benchmarking-pipelines/src/toil_bdg/benchmarking/single_node/align_and_call.py#L90

and

https://github.com/fnothaft/toil-lib/commit/1a7d9379640694aef07efab3505a32d78802b7e9#diff-5f383740058d844c84c0fbbf10901c0eR241

and

https://github.com/fnothaft/toil-lib/commit/b177411f2ae897f4d35ca3e64ab0ca96bd8daadc#diff-1e5f285554ea7f1b142b46addb894d5eR69

I'm not sure how all the branches relate though, so I'm not able to follow along at home.

**Comment by heuermh** [comment]
Closing as WontFix
