### ISSUE TITLE
FileNotFoundException while loading file from HDFS

### ISSUE THREAD

**Issue by shibuvp** [bigdatagenomics/cannoli#66]
I'm getting FileNotFoundException while running bwa via cannoli.
The command is 
`./bin/cannoli-submit --master yarn-cluster --driver-memory 2g --executor-memory 4g  -- bwa  hdfs://master.hdp:8020/genomics/SampleFastqFile1.fastq  hdfs://master.hdp:8020/opt/121.sam sample -index /Data/HumanBase/hg19/hg19.fa`

The error,
`17/08/29 16:49:03 INFO ContainerManagementProtocolProxy: Opening proxy : slave3.hdp:45454
17/08/29 16:49:04 INFO YarnClusterSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (slave.hdp:37022) with ID 1
17/08/29 16:49:04 INFO BlockManagerMasterEndpoint: Registering block manager slave.hdp:39003 with 2.7 GB RAM, BlockManagerId(1, slave.hdp, 39003)
17/08/29 16:49:08 INFO AMRMClientImpl: Received new token for : slave1.hdp:45454
17/08/29 16:49:08 INFO YarnAllocator: Received 1 containers from YARN, launching executors on 0 of them.
17/08/29 16:49:12 INFO YarnClusterSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (slave3.hdp:39136) with ID 2
17/08/29 16:49:12 INFO BlockManagerMasterEndpoint: Registering block manager slave3.hdp:41459 with 2.7 GB RAM, BlockManagerId(2, slave3.hdp, 41459)
17/08/29 16:49:12 INFO YarnClusterSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.8
17/08/29 16:49:12 INFO YarnClusterScheduler: YarnClusterScheduler.postStartHook done
17/08/29 16:49:12 INFO ADAMContext: Loading hdfs://master.hdp:8020/opt/original_samfile_gvs_sorted.bam.adam as Parquet containing Fragments.
Command body threw exception:
java.io.FileNotFoundException: Couldn't find any files matching hdfs://master.hdp:8020/opt/original_samfile_gvs_sorted.bam.adam
17/08/29 16:49:13 INFO Bwa: Overall Duration: 12.83 secs
17/08/29 16:49:13 ERROR ApplicationMaster: User class threw exception: java.io.FileNotFoundException: Couldn't find any files matching hdfs://master.hdp:8020/opt/original_samfile_gvs_sorted.bam.adam
java.io.FileNotFoundException: Couldn't find any files matching hdfs://master.hdp:8020/opt/original_samfile_gvs_sorted.bam.adam
	at org.bdgenomics.adam.rdd.ADAMContext.getFsAndFilesWithFilter(ADAMContext.scala:1354)
	at org.bdgenomics.adam.rdd.ADAMContext.loadAvroPrograms(ADAMContext.scala:1152)
	at org.bdgenomics.adam.rdd.ADAMContext.loadParquetFragments(ADAMContext.scala:2512)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFragments$1.apply(ADAMContext.scala:2904)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFragments$1.apply(ADAMContext.scala:2882)
	at scala.Option.fold(Option.scala:157)
	at org.apache.spark.rdd.Timer.time(Timer.scala:48)
	at org.bdgenomics.adam.rdd.ADAMContext.loadFragments(ADAMContext.scala:2882)
	at org.bdgenomics.cannoli.cli.Bwa.run(Bwa.scala:114)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:55)
	at org.bdgenomics.cannoli.cli.Bwa.run(Bwa.scala:101)
	at org.bdgenomics.cannoli.cli.Cannoli.apply(Cannoli.scala:103)
	at org.bdgenomics.cannoli.cli.Cannoli$.main(Cannoli.scala:41)
	at org.bdgenomics.cannoli.cli.Cannoli.main(Cannoli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:559)
17/08/29 16:49:13 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.io.FileNotFoundException: Couldn't find any files matching hdfs://master.hdp:8020/opt/original_samfile_gvs_sorted.bam.adam)
17/08/29 16:49:13 INFO SparkContext: Invoking stop() from shutdown hook
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/metrics/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage/kill,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/api,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/static,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/threadDump/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/threadDump,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/environment/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/environment,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/rdd/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/rdd,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/pool/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/pool,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/job/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/job,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/json,null}
17/08/29 16:49:13 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs,null}
17/08/29 16:49:13 INFO SparkUI: Stopped Spark web UI at http://172.16.2.124:45250
17/08/29 16:49:13 INFO YarnAllocator: Driver requested a total number of 0 executor(s).
17/08/29 16:49:13 INFO YarnClusterSchedulerBackend: Shutting down all executors
17/08/29 16:49:13 INFO YarnClusterSchedulerBackend: Asking each executor to shut down
17/08/29 16:49:13 INFO SchedulerExtensionServices: Stopping SchedulerExtensionServices
(serviceOption=None,
 services=List(),
 started=false)
17/08/29 16:49:13 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/08/29 16:49:13 INFO MemoryStore: MemoryStore cleared
17/08/29 16:49:13 INFO BlockManager: BlockManager stopped
17/08/29 16:49:13 INFO BlockManagerMaster: BlockManagerMaster stopped
17/08/29 16:49:13 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/08/29 16:49:13 INFO SparkContext: Successfully stopped SparkContext
17/08/29 16:49:13 INFO ShutdownHookManager: Shutdown hook called
17/08/29 16:49:13 INFO ShutdownHookManager: Deleting directory /var/hadoop/yarn/local/usercache/root/appcache/application_1504003590244_0003/spark-efeec220-d6bd-49bd-aacc-fe9c1492ab61
17/08/29 16:49:13 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
17/08/29 16:49:13 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.`

How to fix this?

**Comment by fnothaft** [comment]
Hi @shibuvp! Are you sure that this log is from the same run? I don't see `hdfs://master.hdp:8020/opt/original_samfile_gvs_sorted.bam.adam` being passed as a file path in the command you provided.

**Comment by shibuvp** [comment]
Oh sorry @fnothaft , my mistake. the log which i'm posted here is wrong! 
the actual command is 
`./bin/cannoli-submit --master yarn-cluster --driver-memory 2g --executor-memory 4g -- bwa hdfs://master.hdp:8020/genomics/SampleFastqFile1.fastq hdfs://master.hdp:8020/opt/121.sam sample -index /Data/HumanBase/hg19/hg19.fa`

and the log is,
`17/08/31 10:28:04 INFO ContainerManagementProtocolProxy: Opening proxy : slave1.hdp:45454
17/08/31 10:28:05 INFO YarnClusterSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (slave.hdp:57562) with ID 1
17/08/31 10:28:06 INFO BlockManagerMasterEndpoint: Registering block manager slave.hdp:34563 with 2.7 GB RAM, BlockManagerId(1, slave.hdp, 34563)
17/08/31 10:28:06 INFO YarnClusterSchedulerBackend: Registered executor NettyRpcEndpointRef(null) (slave1.hdp:37226) with ID 2
17/08/31 10:28:06 INFO BlockManagerMasterEndpoint: Registering block manager slave1.hdp:32801 with 2.7 GB RAM, BlockManagerId(2, slave1.hdp, 32801)
17/08/31 10:28:06 INFO YarnClusterSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.8
17/08/31 10:28:06 INFO YarnClusterScheduler: YarnClusterScheduler.postStartHook done
17/08/31 10:28:06 INFO ADAMContext: Loading hdfs://master.hdp:8020/genomics/SampleFastqFile1.fastq as Parquet containing Fragments.
Command body threw exception:
java.io.FileNotFoundException: Couldn't find any files matching hdfs://master.hdp:8020/genomics/SampleFastqFile1.fastq
17/08/31 10:28:06 INFO Bwa: Overall Duration: 5.22 secs
17/08/31 10:28:06 ERROR ApplicationMaster: User class threw exception: java.io.FileNotFoundException: Couldn't find any files matching hdfs://master.hdp:8020/genomics/SampleFastqFile1.fastq
java.io.FileNotFoundException: Couldn't find any files matching hdfs://master.hdp:8020/genomics/SampleFastqFile1.fastq
	at org.bdgenomics.adam.rdd.ADAMContext.getFsAndFilesWithFilter(ADAMContext.scala:1354)
	at org.bdgenomics.adam.rdd.ADAMContext.loadAvroSequenceDictionary(ADAMContext.scala:1164)
	at org.bdgenomics.adam.rdd.ADAMContext.loadParquetFragments(ADAMContext.scala:2506)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFragments$1.apply(ADAMContext.scala:2904)
	at org.bdgenomics.adam.rdd.ADAMContext$$anonfun$loadFragments$1.apply(ADAMContext.scala:2882)
	at scala.Option.fold(Option.scala:157)
	at org.apache.spark.rdd.Timer.time(Timer.scala:48)
	at org.bdgenomics.adam.rdd.ADAMContext.loadFragments(ADAMContext.scala:2882)
	at org.bdgenomics.cannoli.cli.Bwa.run(Bwa.scala:114)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:55)
	at org.bdgenomics.cannoli.cli.Bwa.run(Bwa.scala:101)
	at org.bdgenomics.cannoli.cli.Cannoli.apply(Cannoli.scala:103)
	at org.bdgenomics.cannoli.cli.Cannoli$.main(Cannoli.scala:41)
	at org.bdgenomics.cannoli.cli.Cannoli.main(Cannoli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:559)
17/08/31 10:28:06 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.io.FileNotFoundException: Couldn't find any files matching hdfs://master.hdp:8020/genomics/SampleFastqFile1.fastq)
17/08/31 10:28:06 INFO SparkContext: Invoking stop() from shutdown hook
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/metrics/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage/kill,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/api,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/static,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/threadDump/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/threadDump,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/environment/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/environment,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/rdd/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/rdd,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/pool/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/pool,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/job/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/job,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/json,null}
17/08/31 10:28:06 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs,null}
17/08/31 10:28:06 INFO SparkUI: Stopped Spark web UI at http://172.16.2.125:40574
17/08/31 10:28:06 INFO YarnAllocator: Driver requested a total number of 0 executor(s).
17/08/31 10:28:06 INFO YarnClusterSchedulerBackend: Shutting down all executors
17/08/31 10:28:06 INFO YarnClusterSchedulerBackend: Asking each executor to shut down
17/08/31 10:28:06 INFO SchedulerExtensionServices: Stopping SchedulerExtensionServices
(serviceOption=None,
 services=List(),
 started=false)
17/08/31 10:28:06 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/08/31 10:28:06 INFO MemoryStore: MemoryStore cleared
17/08/31 10:28:06 INFO BlockManager: BlockManager stopped
17/08/31 10:28:06 INFO BlockManagerMaster: BlockManagerMaster stopped
17/08/31 10:28:06 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/08/31 10:28:06 INFO SparkContext: Successfully stopped SparkContext
17/08/31 10:28:06 INFO ShutdownHookManager: Shutdown hook called
17/08/31 10:28:06 INFO ShutdownHookManager: Deleting directory /var/hadoop/yarn/local/usercache/root/appcache/application_1504003590244_0029/spark-8e104abd-3ef9-4a19-984b-a52e6605fd25`

**Comment by shibuvp** [comment]
I think it could be a problem of permission issue of directory called 'genomics'

**Comment by heuermh** [comment]
For better or worse, the `ADAMContext.loadFragments` method expects files in interleaved FASTQ format with file extension `ifq`.

See https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L2927

**Comment by heuermh** [comment]
Closing as WontFix.  Please create an issue upstream in ADAM if you think that file extension checking in `ADAMContext.loadFragments` should change.
