### ISSUE TITLE
Cannoli Command

### ISSUE THREAD

**Issue by Rokshan2016** [bigdatagenomics/cannoli#73]
Hi, 
I want to align my fastq file with reference genome. I indexed the reference genome with bwa. I got five different files now-Homo_sapiens_assembly18.fasta.sa
Homo_sapiens_assembly18.fasta.ann
Homo_sapiens_assembly18.fasta.amb
Homo_sapiens_assembly18.fasta.pac
Homo_sapiens_assembly18.fasta.bwt). 
Which one should I use to write the cannoli command. 

Any suggestion will be helpful.

Thanks

**Comment by Rokshan2016** [comment]
Hi, 
This is my cannoli command . Just want to make sure its the right one-

./cannoli-submit bwa hdfs:///user/rokshan.jahan/SRR1517848.adam/ hdfs:///user/rokshan.jahan/Homo.adam/ hdfs:///user/rokshan.jahan/Homo_sapiens_assembly38_.fasta/ hdfs:///user/rokshan.jahan/Homo_sapiens_assembly38.dict/

**Comment by fnothaft** [comment]
Looks reasonable. Did you encounter any errors when running it?

**Comment by Rokshan2016** [comment]
rokshan.jahan@ip-10-48-3-63 bin]$ yarn application -status 1502373891039_22775
17/09/21 10:43:33 INFO client.RMProxy: Connecting to ResourceManager at ip-10-48-3-5.ips.local/10.48.3.5:8032
Exception in thread "main" java.lang.IllegalArgumentException: Invalid ApplicationId prefix: 1502373891039_22775. The valid ApplicationId should start with prefix application
        at org.apache.hadoop.yarn.util.ConverterUtils.toApplicationId(ConverterUtils.java:200)
        at org.apache.hadoop.yarn.client.cli.ApplicationCLI.printApplicationReport(ApplicationCLI.java:476)
        at org.apache.hadoop.yarn.client.cli.ApplicationCLI.run(ApplicationCLI.java:158)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
        at org.apache.hadoop.yarn.client.cli.ApplicationCLI.main(ApplicationCLI.java:81)
[rokshan.jahan@ip-10-48-3-63 bin]$ yarn application -kill application_ 1502373891039_22775
17/09/21 10:45:08 INFO client.RMProxy: Connecting to ResourceManager at ip-10-48-3-5.ips.local/10.48.3.5:8032
usage: application
 -appStates <States>             Works with -list to filter applications
                                 based on input comma-separated list of
                                 application states. The valid application
                                 state can be one of the following:
                                 ALL,NEW,NEW_SAVING,SUBMITTED,ACCEPTED,RUN
                                 NING,FINISHED,FAILED,KILLED
 -appTypes <Types>               Works with -list to filter applications
                                 based on input comma-separated list of
                                 application types.
 -help                           Displays help for all commands.
 -kill <Application ID>          Kills the application.
 -list                           List applications. Supports optional use
                                 of -appTypes to filter applications based
                                 on application type, and -appStates to
                                 filter applications based on application
                                 state.
 -movetoqueue <Application ID>   Moves the application to a different
                                 queue.
 -queue <Queue Name>             Works with the movetoqueue command to
                                 specify which queue to move an
                                 application to.
 -status <Application ID>        Prints the status of the application.
[rokshan.jahan@ip-10-48-3-63 bin]$ yarn application -kill application_1502373891039_22775
17/09/21 10:45:19 INFO client.RMProxy: Connecting to ResourceManager at ip-10-48-3-5.ips.local/10.48.3.5:8032
Killing application application_1502373891039_22775
17/09/21 10:45:19 INFO impl.YarnClientImpl: Killed application application_1502373891039_22775
[rokshan.jahan@ip-10-48-3-63 bin]$ yarn application -kill application_1502373891039_22774
17/09/21 10:46:04 INFO client.RMProxy: Connecting to ResourceManager at ip-10-48-3-5.ips.local/10.48.3.5:8032
Killing application application_1502373891039_22774
17/09/21 10:46:05 INFO impl.YarnClientImpl: Killed application application_1502373891039_22774
[rokshan.jahan@ip-10-48-3-63 bin]$

**Comment by Rokshan2016** [comment]
This is the error

**Comment by fnothaft** [comment]
As a generalization, its difficult for us to advise whether your parameters are right without knowing about your sample, compute environment, issues you've encountered, etc. Otherwise, we don't have enough information to provide meaningful guidance. If you have specific questions or errors you've encountered, we can be more helpful.

**Comment by Rokshan2016** [comment]
Sorry wrong one


17/09/21 11:43:46 INFO cli.Cannoli: Cannoli invoked with args: "bwa" "hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam/" "hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo.adam/" "hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo_sapiens_assembly38_.fasta/" "hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo_sapiens_assembly38.dict/" "-fragments" "-add_indices"
Too many arguments: hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo_sapiens_assembly38.dict/
 INPUT                                                           : Location to pipe from, in interleaved FASTQ format.
 OUTPUT                                                          : Location to pipe to.
 SAMPLE                                                          : Sample ID.
 -add_indices                                                    : Adds index files via SparkFiles mechanism.
 -bwa_path VAL                                                   : Path to the BWA executable. Defaults to bwa.
 -defer_merging                                                  : Defers merging single file output.
 -disable_fast_concat                                            : Disables the parallel file concatenation engine.
 -docker_cmd VAL                                                 : The docker command to run. Defaults to 'docker'.
 -docker_image VAL                                               : Docker image to use. Defaults to quay.io/ucsc_cgl/bwa:0.7.12--256539928ea162949d8a6
                                                                   5ca5c79a72ef557ce7c.
 -force_load_ifastq                                              : Forces loading using interleaved FASTQ.
 -force_load_parquet                                             : Forces loading using Parquet.
 -fragments                                                      : Saves OUTPUT as Fragments in Parquet. Exclusive of -single.
 -h (-help, --help, -?)                                          : Print help
 -index VAL                                                      : Path to the bwa index to be searched, e.g. <ebwt> in bwa [options]* <ebwt> ...
 -parquet_block_size N                                           : Parquet block size (default = 128mb)
 -parquet_compression_codec [UNCOMPRESSED | SNAPPY | GZIP | LZO] : Parquet compression codec
 -parquet_disable_dictionary                                     : Disable dictionary encoding
 -parquet_logging_level VAL                                      : Parquet logging level (default = severe)
 -parquet_page_size N                                            : Parquet page size (default = 1mb)
 -print_metrics                                                  : Print metrics to the log on completion
 -sequence_dictionary VAL                                        : Path to the sequence dictionary.
 -single                                                         : Saves OUTPUT as single file. Exclusive of -fragments.
 -use_docker                                                     : If true, uses Docker to launch BWA. If false, uses the BWA executable path.
[rokshan.jahan@ip-10-48-3-63 bin]$

**Comment by Rokshan2016** [comment]
Actually this is the error-  Too many arguments: hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo_sapiens_assembly38.dict/
so what does it means?

**Comment by fnothaft** [comment]
Hi @Rokshan2016. You're missing the sample ID in your command, and the optional arguments should be prefaced with their command line flag. I.e., your command should be:

```
./cannoli-submit bwa \
  hdfs:///user/rokshan.jahan/SRR1517848.adam/ hdfs:///user/rokshan.jahan/Homo.adam/ \
  hdfs:///user/rokshan.jahan/Homo_sapiens_assembly38_.fasta/ \
  SRR1517848 \
  -sequence_dictionary hdfs:///user/rokshan.jahan/Homo_sapiens_assembly38.dict/
```

**Comment by Rokshan2016** [comment]
Ok. Thank you. Will try this way.

Actually this are the data I used
This is the dam file --SRR1517848.adam ( Converted from .fastq to .adam)
Homo.adam ( Reference genome in .adam format) 
Homo_sapiens_assembly38_.fasta (Reference genome in .fasta)
Homo_sapiens_assembly38.dict( Reference genome .dict file)

**Comment by fnothaft** [comment]
You'll also need to put `-index` before the path to your FASTA. You'll probably also need to add the `-add_indices` flag, since your index is in HDFS.

**Comment by Rokshan2016** [comment]
ok . Will try that

Thank you

**Comment by Rokshan2016** [comment]
Is this looks ok right now  👍 

./cannoli-submit bwa \ hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam/ hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo.adam/ \ -index -add_indices hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo_sapiens_assembly38_.fasta/ \ SRR1517848 \ -sequence_dictionary hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo_sapiens_assembly38.dict/

**Comment by Rokshan2016** [comment]
./cannoli-submit bwa hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam/ hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo.adam/ -index  hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo_sapiens_assembly38_.fasta/ -add_indices SRR1517848 -sequence_dictionary hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homo_sapiens_assembly38.dict/

**Comment by Rokshan2016** [comment]
I am having this error now-
17/09/21 13:34:55 INFO scheduler.TaskSetManager: Lost task 1.2 in stage 0.0 (TID 8) on ip-10-48-3-65.ips.local, executor 4: org.apache.parquet.io.InvalidRecordException (Parquet/Avro schema mismatch. Avro field 'readInFragment' not found.) [duplicate 6]
Sep 21,

**Comment by Rokshan2016** [comment]
I used this command:


./cannoli-submit bwa hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/SRR1517848.adam hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/Homos_sep12.adam SRR1517848 -index  hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/data/Homo_sapiens_assembly18.fasta -sequence_dictionary  hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/hg38.dict -fragments   -add_indices

**Comment by Rokshan2016** [comment]
It is showing following error:

Command body threw exception:
java.lang.IllegalArgumentException: Can not create a Path from an empty string
17/09/21 18:34:30 INFO cli.Bwa: Overall Duration: 10.24 secs
Exception in thread "main" java.lang.IllegalArgumentException: Can not create a Path from an empty string

**Comment by Rokshan2016** [comment]
It will be really great if someone can help me with this.

Thanks!

**Comment by Rokshan2016** [comment]
at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.parquet.io.InvalidRecordException: Parquet/Avro schema mismatch. Avro field 'readInFragment' not found.
        at org.apache.parquet.avro.AvroIndexedRecordConverter.getAvroField(AvroIndexedRecordConverter.java:128)
